apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy_v1
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec:
      replicas: 4
      containers:
      - name: site
        image: $user/conversao-temperatura:v1.0.1
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    matchLabels:
      app: web
    ports:
      - port: 80
        protocol: TCP
        nodePort: 30000
    type: NodePort